### PR TITLE
Include more details in the ApiConnectionException message

### LINKED ISSUE #313: Bug located in ApiConnectionException
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When a connection error occurs, no useful information is returned, only the name of the exception

### 📝 Steps to reproduce

Provide an invalid path for a connection request with valid credentials for the host
Observe unhelpful response

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
Package                          Version
-------------------------------- -----------
<INTERNAL API PACKAGE>           0.1.0.dev11
ansys-openapi-common             1.2.0
anyio                            3.6.2
attrs                            22.2.0
CacheControl                     0.12.11
certifi                          2022.12.7
cffi                             1.15.1
charset-normalizer               3.0.1
cleo                             2.0.1
click                            8.1.3
colorama                         0.4.6
crashtest                        0.4.1
cryptography                     39.0.0
distlib                          0.3.6
dulwich                          0.20.50
fastapi                          0.89.1
fastapi-pagination               0.11.3
filelock                         3.9.0
h11                              0.14.0
html5lib                         1.1
httptools                        0.5.0
idna                             3.4
importlib-metadata               6.0.0
jaraco.classes                   3.2.3
jsonschema                       4.17.3
keyring                          23.13.1
lockfile                         0.12.2
more-itertools                   9.0.0
msgpack                          1.0.4
ntlm-auth                        1.5.0
packaging                        23.0
pexpect                          4.8.0
pip                              22.3.1
pkginfo                          1.9.6
platformdirs                     2.6.2
poetry                           1.3.2
poetry-core                      1.4.0
poetry-plugin-export             1.2.0
ptyprocess                       0.7.0
pycparser                        2.21
pydantic                         1.10.4
pyparsing                        3.0.9
pypiwin32                        223
pyrsistent                       0.19.3
python-dateutil                  2.8.2
python-dotenv                    0.21.0
pywin32                          305
pywin32-ctypes                   0.2.0
PyYAML                           6.0
rapidfuzz                        2.13.7
requests                         2.28.2
requests-negotiate-sspi          0.5.2
requests-ntlm                    1.1.0
requests-toolbelt                0.10.1
setuptools                       65.6.3
shellingham                      1.5.0.post1
six                              1.16.0
sniffio                          1.3.0
starlette                        0.22.0
tomli                            2.0.1
tomlkit                          0.11.6
trove-classifiers                2023.1.12
typing_extensions                4.4.0
urllib3                          1.26.14
uvicorn                          0.20.0
virtualenv                       20.17.1
watchfiles                       0.18.1
webencodings                     0.5.1
websockets                       10.4
wheel                            0.38.4
zipp                             3.11.0
```

### PR DESCRIPTION
**Pull request by Andy-Grigg**
Closes #313 

Improves the message included in an ApiConnectionException to include all the information that is passed into the exception constructor, instead of just the response from the server.

Also adds the URL that resulted in the exception, resulting in a stack trace that looks like this:

```
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Roaming\JetBrains\PyCharm2022.2\scratches\scratch_5.py", line 6, in <module>
    conn = ApiClientFactory(api_url=url).with_credentials(**creds).connect()
  File "C:\git\pyansys\openapi-common\src\ansys\openapi\common\_session.py", line 213, in with_credentials
    if self.__test_connection():
  File "C:\git\pyansys\openapi-common\src\ansys\openapi\common\_session.py", line 317, in __test_connection
    raise ApiConnectionException(
ansys.openapi.common._exceptions.ApiConnectionException: Request url 'http://hostname/invalid/path' failed with reason 404: Not Found.
The following was returned by the server:
<!DOCTYPE html>
<html>
...
```

In some cases the content returned by the server would have been enough to figure out the cause of the issue, but not always. We now always raise an exception with at least the following:

* url
* status code
* reason phrase

If any content was returned by the server, it is also included in the exception.

### CODE REVIEW

**Review by da1910 — APPROVED** [review]
Looks as expected. Only thing we might want to consider is including the actual failing request/response as properties of the exception, things like headers are likely to be helpful with debugging auth issues.

**Comment by ludovicsteinbach** [comment]
Renaming `message` to `content` is a breaking change that will affect private packages

**Comment by Andy-Grigg** [comment]
> Renaming `message` to `content` is a breaking change that will affect private packages

That's a very good point. We could leave it as 'message', but it will be a bit confusing that it essentially repurposes the base exception keyword argument.

We might not have a choice though. I might argue that there are no actual packages that are using `ApiConnectionException` right now (BomAnalytics uses `ApiException`, am I missing anything?), but that's not really good enough if we're obeying our versioning rules.

**Comment by Andy-Grigg** [comment]
Changes should now be non-breaking. I haven't added the actual response object to the exception itself, my rationale being that it's another arg (that in reality could replace 3 of them, but not if we want a non-breaking change), and that if you're actually trying to fix the issue, it's trivial to just step up one level in the call stack to see what the problem is.

**Review by da1910 — APPROVED** [review]

**Comment by Andy-Grigg** [comment]
After further discussion/thinking, we've decided to go ahead with breaking changes, and the response object is now the only thing passed to the exception. Extraction of relevant information is now handled in the exception itself.

**Pull request merged**
